# ~/.config/zsh/aliases.zsh - All aliases

# Modern CLI replacements
(( $+commands[bat] )) && alias cat='bat' more='bat' less='bat'
(( $+commands[eza] )) && alias ls='eza --icons=always'
(( $+commands[nvim] )) && alias vim='nvim' vimdiff='nvim -d'
(( $+commands[kubectl] )) && alias k='kubectl'

# Git
alias g='git'
alias ga='git add'
alias gaf='git ls-files -m -o --exclude-standard | fzf --print0 -m | xargs -0 -t -o git add'
alias gap='git add -AN && git add -p'
alias gau='git add -u'
alias gb='git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)"'
alias gcb='git checkout -b'
alias gcd='cd $(git rev-parse --show-toplevel)'
alias gcf='git clean -f'
alias gcm='git commit -m'
alias gcp='git checkout -p'
alias gcv='git commit -v'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdn='git diff --name-only'
alias gdom='git diff $(git symbolic-ref refs/remotes/origin/HEAD | sed "s@^refs/remotes/origin/@@")...'
alias glom='git log origin/main...'
alias gds='git diff --staged'
alias gdst='git diff --stat'
alias gdu='git diff @{upstream}'
alias gf='git fetch'
alias gfom='git fetch origin main'
alias gg='gau; git cane'
alias ggg='gau; git cane; gpfwln'
alias girl='git reflog -n30'
alias gj='git status'
alias gjuno='git status -uno'
alias gl='git log --pretty=format:"%C(yellow)%h %Cred%ad %Cblue%<(20,trunc)%aN %Creset%s %C(auto)%d" --date=format:"%Y-%m-%d %H:%M:%S" --decorate -n 15'
alias gll='git log --oneline --stat -n 5'
alias gly='git log --pretty=format:"%C(yellow)%h %Cred%ad %Cblue%<(20)%an%Cgreen%d %Creset%s" --date=format:"%Y-%m-%d %H:%M:%S" -n 15 | yank'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gmom='git merge origin/main'
alias gp='git pull'
alias gpa='git pull --autostash'
alias gpn='git push --no-verify'
alias gpfwl='git push --force-with-lease'
alias gpfwln='git push --force-with-lease --no-verify'
alias gpomr='function _gpomr() { git pull origin main --rebase="${1:-true}" -Xignore-whitespace; }; _gpomr'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grd='git range-diff @{u}...@'
alias grh='git reset --hard'
alias grs='git restore --staged'
alias gret='git rebase --edit-todo'
alias griom='git rebase -i origin/main'
alias gr='git review'
alias gs-='git switch -'
alias gs='git switch'
alias gsc='git switch -c'
alias gsh='git show'
alias gwl='git worktree list'
alias gwa='git worktree add'
alias gmp='gsm && gp'
alias gto='git open'
alias mom='git fetch && git merge origin/main'
alias mop='git fetch && git merge origin/preprod'
alias mog='git fetch && git merge origin/green --no-edit'
alias rom='git fetch && git rebase -i origin/main'
alias germ='git log origin/main..HEAD --author="benjamin liu" --oneline'
alias dots='/usr/bin/git --git-dir=$HOME/src/dots/ --work-tree=$HOME'
alias dj='dots status'
alias dl='dots log --pretty=format:"%C(yellow)%h %Cred%ad %Cblue%<(20,trunc)%aN %Creset%s %C(auto)%d" --date=format:"%Y-%m-%d %H:%M:%S" --decorate -n 15'

# jj (jujutsu)
alias j='jj'
alias jdu='jj du'
alias jdu-='jj du-'
alias jst='jj st'
alias jsp='jj split'
alias jsh='jj show'
alias jl='jj l'
alias jn='jj new'
alias je='jj edit'
alias jbl='jj bookmark list'
alias jd='jj diff'
alias jdm='jj describe -m'
alias jde='jj describe --edit'
alias ju='jj undo'
alias jsq='jj squash'
alias jp='jj push'
alias jp-='jj push-'
alias jf='jj fetch'
alias jpb='jj pushb'
alias jpb-='jj pushb-'
alias jui='jjui'

# GitHub/Graphite PRs
alias gtdraft='gt s -fq'
alias gtopen='gt s -fqp'
alias prdraft='gt s -fq'
alias propen='gt s -fqp'
alias prview='gh pr view -w'
alias prd='prdraft'
alias pro='propen'
alias prv='prview'
alias prdv='prdraft && prview'
alias prov='propen && prview'
alias prl='gh pr list --state open --author "@me" --limit 100'

# Kubernetes
alias kgp='k get pods'
alias kgpw='k get pods -w'
alias kns='kubens'
alias ktx='kubectx'
alias kctx='kubectx'
alias kx='f() { [ "$1" ] && kubectl config use-context $1 || kubectl config current-context ; } ; f'
alias kn='f() { [ "$1" ] && kubectl config set-context --current --namespace $1 || kubectl config view --minify | grep namespace | cut -d" " -f6 ; } ; f'

# General
alias targets='make -qp | awk -F'\'':'\'' '\''/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}'\'' | sort -u'
alias pacman='yay'
alias ta='tmux attach'
alias ez='exec zsh'
alias bubu='brew update && brew upgrade'
alias mt='make test'
alias tf='terraform'
alias grep='grep --color=auto'
alias c='claude'
